-- AlterEnum
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'RISK_RECOMPUTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'ALGORITHM_CONFIG_CHANGED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'PATTERN_MATCHED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'RECOMMENDATION_DRAFTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'RECOMMENDATION_DISMISSED';
